const photo = [
  {
    id: 1,
    title: "sleeping",
    category: "sleeping",
    img: "/assets/cat_sleeping1.jpg",
    date: "May 03 2024",
    desc: "",
  },
  {
    id: 2,
    title: "playing",
    category: "playing",
    img: "/assets/cat_playing2.jpg",
    date: "April 03 2024",
    desc: "",
  },
  {
    id: 3,
    title: "studying",
    category: "studying",
    img: "/assets/cat_studying1.jpg",
    date: "Oct 31 2023",
    desc: "",
  },
  {
    id: 4,
    title: "sleeping",
    category: "sleeping",
    img: "/assets/cat_sleeping2.jpg",
    date: "March 19 2024",
    desc: "",
  },
  {
    id: 5,
    title: "sleeping",
    category: "sleeping",
    img: "/assets/cat_sleeping3.jpg",
    date: "Feb 19 2024",
    desc: "",
  },
  {
    id: 6,
    title: "studying",
    category: "studying",
    img: "/assets/cat_studying2.jpg",
    date: "June 23 2023",
    desc: "",
  },
  {
    id: 12,
    title: "video",
    category: "video",
    video: "/assets/cat_video1.mov",
    date: "March 07 2024",
    desc: "",
  },
  {
    id: 7,
    title: "playing",
    category: "playing",
    img: "/assets/cat_playing1.jpg",
    date: "May 22 2024",
    desc: "",
  },
  {
    id: 8,
    title: "studying",
    category: "studying",
    img: "/assets/cat_studying3.jpg",
    date: "June 20 2023",
    desc: "",
  },
  {
    id: 13,
    title: "video",
    category: "video",
    video: "/assets/cat_video2.mov",
    date: "June 22 2023",
    desc: "",
  },
  {
    id: 9,
    title: "selfie",
    category: "selfie",
    img: "/assets/cat_selfie.jpg",
    date: "Feb 22 2024",
    desc: "",
  },
  {
    id: 10,
    title: "angry",
    category: "angry",
    img: "/assets/cat_angry.jpg",
    date: "May 06 2024",
    desc: "",
  },
  {
    id: 11,
    title: "playing",
    category: "playing",
    img: "/assets/cat_playing3.jpg",
    date: "June 11 2024",
    desc: "",
  },
  {
    id: 14,
    title: "playing",
    category: "playing",
    img: "/assets/cat_playing4.jpg",
    date: "",
    desc: "",
  },
  {
    id: 15,
    title: "sleeping",
    category: "sleeping",
    img: "/assets/cat_sleeping6.jpg",
    date: "",
    desc: "",
  },
  {
    id: 16,
    title: "sleeping",
    category: "sleeping",
    img: "/assets/cat_sleeping7.jpg",
    date: "",
    desc: "",
  },
  {
    id: 17,
    title: "",
    category: "playing",
    img: "/assets/cat_playing5.jpg",
    date: "",
    desc: "",
  },
  {
    id: 18,
    title: "",
    category: "playing",
    img: "/assets/cat_eating.jpg",
    date: "",
    desc: "",
  },
  {
    id: 19,
    title: "",
    category: "playing",
    img: "/assets/cat_playing6.jpg",
    date: "",
    desc: "",
  },
  {
    id: 20,
    title: "",
    category: "playing",
    img: "/assets/cat_playing7.jpg",
    date: "",
    desc: "",
  },
];

export default photo;
